PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCA_MV_GOS_BOAS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCA_MV_GOS_BOAS-BO_NAME .
    FIELD ZCA_MV_GOS_BOAS-NTEXT .
    FIELD ZCA_MV_GOS_BOAS-TCODE .
    FIELD ZCA_MV_GOS_BOAS-PRIO_ATTCH_NAME .
    FIELD ZCA_MV_GOS_BOAS-CLASS_NAME_CONSUMER .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZCA_MV_GOS_BOAS ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCA_MV_GOS_BOAS-BO_NAME .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
