*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZCA_MV_GOS_BOAS.................................*
FORM GET_DATA_ZCA_MV_GOS_BOAS.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCA_GOS_BOAS WHERE
(VIM_WHERETAB) .
    CLEAR ZCA_MV_GOS_BOAS .
ZCA_MV_GOS_BOAS-MANDT =
ZCA_GOS_BOAS-MANDT .
ZCA_MV_GOS_BOAS-BO_NAME =
ZCA_GOS_BOAS-BO_NAME .
ZCA_MV_GOS_BOAS-CLASS_NAME_CONSUMER =
ZCA_GOS_BOAS-CLASS_NAME_CONSUMER .
ZCA_MV_GOS_BOAS-TCODE =
ZCA_GOS_BOAS-TCODE .
ZCA_MV_GOS_BOAS-PRIO_ATTCH_NAME =
ZCA_GOS_BOAS-PRIO_ATTCH_NAME .
    SELECT SINGLE * FROM TOJTB WHERE
NAME = ZCA_GOS_BOAS-BO_NAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TOJTT WHERE
NAME = TOJTB-NAME AND
LANGUAGE = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCA_MV_GOS_BOAS-NTEXT =
TOJTT-NTEXT .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZCA_MV_GOS_BOAS.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCA_MV_GOS_BOAS .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCA_MV_GOS_BOAS.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCA_MV_GOS_BOAS-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCA_GOS_BOAS WHERE
  BO_NAME = ZCA_MV_GOS_BOAS-BO_NAME .
    IF SY-SUBRC = 0.
    DELETE ZCA_GOS_BOAS .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCA_GOS_BOAS WHERE
  BO_NAME = ZCA_MV_GOS_BOAS-BO_NAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCA_GOS_BOAS.
    ENDIF.
ZCA_GOS_BOAS-MANDT =
ZCA_MV_GOS_BOAS-MANDT .
ZCA_GOS_BOAS-BO_NAME =
ZCA_MV_GOS_BOAS-BO_NAME .
ZCA_GOS_BOAS-CLASS_NAME_CONSUMER =
ZCA_MV_GOS_BOAS-CLASS_NAME_CONSUMER .
ZCA_GOS_BOAS-TCODE =
ZCA_MV_GOS_BOAS-TCODE .
ZCA_GOS_BOAS-PRIO_ATTCH_NAME =
ZCA_MV_GOS_BOAS-PRIO_ATTCH_NAME .
    IF SY-SUBRC = 0.
    UPDATE ZCA_GOS_BOAS ##WARN_OK.
    ELSE.
    INSERT ZCA_GOS_BOAS .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCA_MV_GOS_BOAS-UPD_FLAG,
STATUS_ZCA_MV_GOS_BOAS-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCA_MV_GOS_BOAS.
  SELECT SINGLE * FROM ZCA_GOS_BOAS WHERE
BO_NAME = ZCA_MV_GOS_BOAS-BO_NAME .
ZCA_MV_GOS_BOAS-MANDT =
ZCA_GOS_BOAS-MANDT .
ZCA_MV_GOS_BOAS-BO_NAME =
ZCA_GOS_BOAS-BO_NAME .
ZCA_MV_GOS_BOAS-CLASS_NAME_CONSUMER =
ZCA_GOS_BOAS-CLASS_NAME_CONSUMER .
ZCA_MV_GOS_BOAS-TCODE =
ZCA_GOS_BOAS-TCODE .
ZCA_MV_GOS_BOAS-PRIO_ATTCH_NAME =
ZCA_GOS_BOAS-PRIO_ATTCH_NAME .
    SELECT SINGLE * FROM TOJTB WHERE
NAME = ZCA_GOS_BOAS-BO_NAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TOJTT WHERE
NAME = TOJTB-NAME AND
LANGUAGE = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCA_MV_GOS_BOAS-NTEXT =
TOJTT-NTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCA_MV_GOS_BOAS-NTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCA_MV_GOS_BOAS-NTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCA_MV_GOS_BOAS USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCA_MV_GOS_BOAS-BO_NAME TO
ZCA_GOS_BOAS-BO_NAME .
MOVE ZCA_MV_GOS_BOAS-MANDT TO
ZCA_GOS_BOAS-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCA_GOS_BOAS'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCA_GOS_BOAS TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCA_GOS_BOAS'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZCA_MV_GOS_BOAS USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZCA_GOS_BOAS-MANDT =
ZCA_MV_GOS_BOAS-MANDT .
ZCA_GOS_BOAS-BO_NAME =
ZCA_MV_GOS_BOAS-BO_NAME .
ZCA_GOS_BOAS-CLASS_NAME_CONSUMER =
ZCA_MV_GOS_BOAS-CLASS_NAME_CONSUMER .
ZCA_GOS_BOAS-TCODE =
ZCA_MV_GOS_BOAS-TCODE .
ZCA_GOS_BOAS-PRIO_ATTCH_NAME =
ZCA_MV_GOS_BOAS-PRIO_ATTCH_NAME .
    SELECT SINGLE * FROM TOJTB WHERE
NAME = ZCA_GOS_BOAS-BO_NAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TOJTT WHERE
NAME = TOJTB-NAME AND
LANGUAGE = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZCA_MV_GOS_BOAS-NTEXT =
TOJTT-NTEXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZCA_MV_GOS_BOAS-NTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZCA_MV_GOS_BOAS-NTEXT .
    ENDIF.
ENDFORM.
