*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZMM_MV_GOSBOASDT................................*
FORM GET_DATA_ZMM_MV_GOSBOASDT.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZMM_GOS_BOASDT WHERE
(VIM_WHERETAB) .
    CLEAR ZMM_MV_GOSBOASDT .
ZMM_MV_GOSBOASDT-MANDT =
ZMM_GOS_BOASDT-MANDT .
ZMM_MV_GOSBOASDT-BO_NAME =
ZMM_GOS_BOASDT-BO_NAME .
ZMM_MV_GOSBOASDT-BSART =
ZMM_GOS_BOASDT-BSART .
ZMM_MV_GOSBOASDT-DOKAR =
ZMM_GOS_BOASDT-DOKAR .
    SELECT * FROM T161 WHERE
BSART = ZMM_GOS_BOASDT-BSART .
      SELECT SINGLE * FROM T161T WHERE
BSTYP = T161-BSTYP AND
BSART = T161-BSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZMM_MV_GOSBOASDT-BATXT =
T161T-BATXT .
      ENDIF.
      EXIT.
    ENDSELECT.
    SELECT SINGLE * FROM TDWA WHERE
DOKAR = ZMM_GOS_BOASDT-DOKAR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TDWAT WHERE
DOKAR = TDWA-DOKAR AND
CVLANG = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZMM_MV_GOSBOASDT-DARTXT =
TDWAT-DARTXT .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM ZCA_GOS_BOAS WHERE
BO_NAME = ZMM_GOS_BOASDT-BO_NAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TOJTB WHERE
NAME = ZCA_GOS_BOAS-BO_NAME .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM TOJTT WHERE
NAME = TOJTB-NAME AND
LANGUAGE = SY-LANGU .
        IF SY-SUBRC EQ 0.
ZMM_MV_GOSBOASDT-NTEXT =
TOJTT-NTEXT .
        ENDIF.
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZMM_MV_GOSBOASDT.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZMM_MV_GOSBOASDT .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZMM_MV_GOSBOASDT.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZMM_MV_GOSBOASDT-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZMM_GOS_BOASDT WHERE
  BO_NAME = ZMM_MV_GOSBOASDT-BO_NAME AND
  BSART = ZMM_MV_GOSBOASDT-BSART .
    IF SY-SUBRC = 0.
    DELETE ZMM_GOS_BOASDT .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZMM_GOS_BOASDT WHERE
  BO_NAME = ZMM_MV_GOSBOASDT-BO_NAME AND
  BSART = ZMM_MV_GOSBOASDT-BSART .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZMM_GOS_BOASDT.
    ENDIF.
ZMM_GOS_BOASDT-MANDT =
ZMM_MV_GOSBOASDT-MANDT .
ZMM_GOS_BOASDT-BO_NAME =
ZMM_MV_GOSBOASDT-BO_NAME .
ZMM_GOS_BOASDT-BSART =
ZMM_MV_GOSBOASDT-BSART .
ZMM_GOS_BOASDT-DOKAR =
ZMM_MV_GOSBOASDT-DOKAR .
    IF SY-SUBRC = 0.
    UPDATE ZMM_GOS_BOASDT ##WARN_OK.
    ELSE.
    INSERT ZMM_GOS_BOASDT .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZMM_MV_GOSBOASDT-UPD_FLAG,
STATUS_ZMM_MV_GOSBOASDT-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZMM_MV_GOSBOASDT.
  SELECT SINGLE * FROM ZMM_GOS_BOASDT WHERE
BO_NAME = ZMM_MV_GOSBOASDT-BO_NAME AND
BSART = ZMM_MV_GOSBOASDT-BSART .
ZMM_MV_GOSBOASDT-MANDT =
ZMM_GOS_BOASDT-MANDT .
ZMM_MV_GOSBOASDT-BO_NAME =
ZMM_GOS_BOASDT-BO_NAME .
ZMM_MV_GOSBOASDT-BSART =
ZMM_GOS_BOASDT-BSART .
ZMM_MV_GOSBOASDT-DOKAR =
ZMM_GOS_BOASDT-DOKAR .
    SELECT * FROM T161 WHERE
BSART = ZMM_GOS_BOASDT-BSART .
      SELECT SINGLE * FROM T161T WHERE
BSTYP = T161-BSTYP AND
BSART = T161-BSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZMM_MV_GOSBOASDT-BATXT =
T161T-BATXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZMM_MV_GOSBOASDT-BATXT .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZMM_MV_GOSBOASDT-BATXT .
    ENDIF.
    SELECT SINGLE * FROM TDWA WHERE
DOKAR = ZMM_GOS_BOASDT-DOKAR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TDWAT WHERE
DOKAR = TDWA-DOKAR AND
CVLANG = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZMM_MV_GOSBOASDT-DARTXT =
TDWAT-DARTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZMM_MV_GOSBOASDT-DARTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZMM_MV_GOSBOASDT-DARTXT .
    ENDIF.
    SELECT SINGLE * FROM ZCA_GOS_BOAS WHERE
BO_NAME = ZMM_GOS_BOASDT-BO_NAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TOJTB WHERE
NAME = ZCA_GOS_BOAS-BO_NAME .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM TOJTT WHERE
NAME = TOJTB-NAME AND
LANGUAGE = SY-LANGU .
        IF SY-SUBRC EQ 0.
ZMM_MV_GOSBOASDT-NTEXT =
TOJTT-NTEXT .
        ELSE.
          CLEAR SY-SUBRC.
          CLEAR ZMM_MV_GOSBOASDT-NTEXT .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZMM_MV_GOSBOASDT-NTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZMM_MV_GOSBOASDT-NTEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZMM_MV_GOSBOASDT USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZMM_MV_GOSBOASDT-BO_NAME TO
ZMM_GOS_BOASDT-BO_NAME .
MOVE ZMM_MV_GOSBOASDT-BSART TO
ZMM_GOS_BOASDT-BSART .
MOVE ZMM_MV_GOSBOASDT-MANDT TO
ZMM_GOS_BOASDT-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZMM_GOS_BOASDT'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZMM_GOS_BOASDT TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZMM_GOS_BOASDT'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZMM_MV_GOSBOASDT USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZMM_GOS_BOASDT-MANDT =
ZMM_MV_GOSBOASDT-MANDT .
ZMM_GOS_BOASDT-BO_NAME =
ZMM_MV_GOSBOASDT-BO_NAME .
ZMM_GOS_BOASDT-BSART =
ZMM_MV_GOSBOASDT-BSART .
ZMM_GOS_BOASDT-DOKAR =
ZMM_MV_GOSBOASDT-DOKAR .
    SELECT * FROM T161 WHERE
BSART = ZMM_GOS_BOASDT-BSART .
      SELECT SINGLE * FROM T161T WHERE
BSTYP = T161-BSTYP AND
BSART = T161-BSART AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZMM_MV_GOSBOASDT-BATXT =
T161T-BATXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZMM_MV_GOSBOASDT-BATXT .
      ENDIF.
      EXIT.
    ENDSELECT.
    IF SY-SUBRC NE 0.
      CLEAR SY-SUBRC.
      CLEAR ZMM_MV_GOSBOASDT-BATXT .
    ENDIF.
    SELECT SINGLE * FROM TDWA WHERE
DOKAR = ZMM_GOS_BOASDT-DOKAR .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TDWAT WHERE
DOKAR = TDWA-DOKAR AND
CVLANG = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZMM_MV_GOSBOASDT-DARTXT =
TDWAT-DARTXT .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZMM_MV_GOSBOASDT-DARTXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZMM_MV_GOSBOASDT-DARTXT .
    ENDIF.
    SELECT SINGLE * FROM ZCA_GOS_BOAS WHERE
BO_NAME = ZMM_GOS_BOASDT-BO_NAME .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TOJTB WHERE
NAME = ZCA_GOS_BOAS-BO_NAME .
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * FROM TOJTT WHERE
NAME = TOJTB-NAME AND
LANGUAGE = SY-LANGU .
        IF SY-SUBRC EQ 0.
ZMM_MV_GOSBOASDT-NTEXT =
TOJTT-NTEXT .
        ELSE.
          CLEAR SY-SUBRC.
          CLEAR ZMM_MV_GOSBOASDT-NTEXT .
        ENDIF.
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZMM_MV_GOSBOASDT-NTEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZMM_MV_GOSBOASDT-NTEXT .
    ENDIF.
ENDFORM.
